version: '3.8'

services:
  postgres:
    image: postgres
    container_name: student_container2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student
    ports:
      - "5430:5432"
